[package]
name = "lang-c-corrode"
version = "0.1.0"
authors = ["Vickenty Fesunov <kent@setattr.net>"]
license = "MIT/Apache-2.0"

[dependencies]
lang-c = { git = "https://github.com/vickenty/lang-c" }
dynamic-arena = "0.1"

[dev-dependencies]
syn = { version = "0.12", features = [ "full" ] }